/*
 * Combined API
 *
 * Endpoints of CRUD of employee and displaying results of student.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing StudentApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class StudentApiTests : IDisposable
    {
        private StudentApi instance;

        public StudentApiTests()
        {
            instance = new StudentApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StudentApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' StudentApi
            //Assert.IsType<StudentApi>(instance);
        }

        /// <summary>
        /// Test ApiStudentGet
        /// </summary>
        [Fact]
        public void ApiStudentGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiStudentGet();
            //Assert.IsType<List<Student>>(response);
        }

        /// <summary>
        /// Test ApiStudentIdGet
        /// </summary>
        [Fact]
        public void ApiStudentIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //var response = instance.ApiStudentIdGet(id);
            //Assert.IsType<List<Student>>(response);
        }
    }
}
