/*
 * Combined API
 *
 * Endpoints of CRUD of employee and displaying results of student.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Employee
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmployeeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Employee
        //private Employee instance;

        public EmployeeTests()
        {
            // TODO uncomment below to create an instance of Employee
            //instance = new Employee();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Employee
        /// </summary>
        [Fact]
        public void EmployeeInstanceTest()
        {
            // TODO uncomment below to test "IsType" Employee
            //Assert.IsType<Employee>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Age'
        /// </summary>
        [Fact]
        public void AgeTest()
        {
            // TODO unit test for the property 'Age'
        }
    }
}
